"""add conversation_id column to documents

Revision ID: cc5f36f3d013
Revises: 
Create Date: 2025-04-16 01:17:15.959567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision: str = 'cc5f36f3d013'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER TABLE for constraints, so we need to use batch mode
    
    # Get the connection
    conn = op.get_bind()
    
    # First add the column without the constraint
    op.add_column('documents', sa.Column('conversation_id', sa.String(), nullable=True))
    
    # We can't add a foreign key constraint directly in SQLite, we would need to:
    # 1. Create a new table with the correct schema
    # 2. Copy data from old table to new table
    # 3. Drop the old table
    # 4. Rename the new table
    
    # Since we're just adding a column that can be null, we'll skip the 
    # foreign key constraint for now. The application logic will handle 
    # the relationship correctly even without the SQL-level constraint.
    
    # If needed, we can recreate the table with proper constraints using batch ops:
    # with op.batch_alter_table('documents', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('conversation_id', sa.String(), nullable=True))
    #     batch_op.create_foreign_key('fk_document_conversation', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Again, for SQLite we need batch operations
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('conversation_id')
    # ### end Alembic commands ###
